### ISSUE TITLE
"Marker set as selectedMarker while not belonging to this map. Ignoring."

### ISSUE THREAD

**Issue by gabrielbunselmeyer** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#1]
Getting this message every time I select a pin.

Seems to me another pin is put on the same location for some reason, as the "SelectedPinChanged" event gets called twice. Also, the default InfoWindow appears for this new pin.

Clustering works fine, though this behavior seems strange/unnecessary.

**Comment by mierzynskim** [comment]
I think https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps.Clustering/commit/ec707418f946e1a8f9c765550faeda8828a2e050 should fix your issue. Please let me know if it helps
