### ISSUE TITLE
No icons are displayed in clusters on ios

### ISSUE THREAD

**Issue by alex-relov** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#10]
icons in the cluster and cluster icons on are displayed. tested on ios simulator

**Comment by mierzynskim** [comment]
@alex-relov Is it the same issue as https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps.Clustering/issues/7? Can you provide some more information?

**Comment by alex-relov** [comment]
> @alex-relov Is it the same issue as #7? Can you provide some more information?


No, this is another problem, the icons on the ios website. unfortunately i have already deleted the project

**Comment by alex-relov** [comment]
@mierzynskim 
No, this is another problem, the icons on the ios website. unfortunately i have already deleted the project
