### ISSUE TITLE
Pin belongs to a cluster

### ISSUE THREAD

**Issue by gnout** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#11]
Is it possible to find out if a pin belongs to a cluster?
At the moment, when I have 10 pins which 5 of them have been grouped into 1 cluster and the other 5 are rendered as single pins, I cannot find out which of the pins are presented as single pins and which of the pins are grouped into a cluster.
Is there a way to distinguish the 2 states of a pin?

**Comment by mierzynskim** [comment]
I think it would be possible to implement it but it's not supported at the moment. I will definitely look at it when the library becomes more stable.
