### ISSUE TITLE
Merge to main repo

### ISSUE THREAD

**Issue by leaguefun** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#13]
There is great feature did for the component, just wonder why not merge into main repo ? by the way, I tried to do binding of google map for android and ios, would you suggest some materials/tutorial ? great thanks.

**Comment by mierzynskim** [comment]
@leaguefun The maintainer of Xamarin.Forms.GoogleMaps insisted on creating a plugin. I'll probably come back to a discussion about merging it to the main repo.

By binding you mean create a binding from native libs?

**Comment by leaguefun** [comment]
It's really great !!

Yes, I find difficulties on creating binding from native libraries, would you having any materials/tutorials for it ? I'm really want to join the development for this project, thanks.

**Comment by mierzynskim** [comment]
I think I haven't used anything more than official Xamarin doc 🙂.

Thanks for you interest! It's kinda early stage of this project but I'd definitely accept cool contributions in the future.

**Comment by leaguefun** [comment]
Got it !
I will try the best to get it works, thanks :D
