### ISSUE TITLE
Changing the ClusteredPins Collection doesn't have any impact on the map

### ISSUE THREAD

**Issue by gnout** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#17]
After the map is loaded with some pins in the ClusteredPins collection, changing the ClusteredPins collection doesn't have any impact on the map. 
I tried to change the icon of a pin when the pin was clicked but nothing happened,
I tried to remove it and add a new one but nothing happened.
(both iOS and Android)

**Comment by mierzynskim** [comment]
It's probably related to https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps.Clustering/issues/8. I'm looking for a reliable way to update pins collection. A workaround for this issue would be to call `Cluster` method every time you change it.
