### ISSUE TITLE
BitmapDescriptorFactory.DefaultMarker(Color.Gray) works only in iOS

### ISSUE THREAD

**Issue by gnout** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#18]
Setting the icon of a pin to `Icon = BitmapDescriptorFactory.DefaultMarker(Color.Gray)` only works in iOS

**Comment by mierzynskim** [comment]
Unfortunately, it's a limitation of google maps api 😞 https://stackoverflow.com/questions/19076124/android-map-marker-color. Hue of a colour you set is zero. You need to set a different colour or create a custom icon.
