### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by leaguefun** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#2]
Hello, I ran the solution on Android Emulator but it can't show up the google map component, would you please advise for any help, thanks.

![screenshot_1549210919](https://user-images.githubusercontent.com/6715863/52179280-14cd4f80-2813-11e9-8871-6c5bfd48eb68.png)

**Comment by mierzynskim** [comment]
You must install google maps on your emulator https://stackoverflow.com/questions/21730758/how-to-run-google-maps-in-the-android-emulator
