### ISSUE TITLE
Android ClusterClicked Handled notworking

### ISSUE THREAD

**Issue by NamCkiku** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#26]
private void Map_ClusterClicked(object sender, Xamarin.Forms.GoogleMaps.Clustering.ClusterClickedEventArgs e)
        {
            e.Handled = true;
        }
        private void MapOnPinClicked(object sender, PinClickedEventArgs e)
        {
            e.Handled = true;
        }

Android not working

**Comment by mierzynskim** [comment]
@NamCkiku I noticed that the implementation is missing. What's use case `Handled` property in your app? I think it may be redundant and I may remove it in future versions

**Comment by mierzynskim** [comment]
It's not supported in both Google Maps clustering libraries so it's removed in b5e98ea
