### ISSUE TITLE
Android Crash while loading Pin icon from bundle.

### ISSUE THREAD

**Issue by NirmalSubedi17** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#31]
> **Failed to decode image. The provided image must be a Bitmap.**

[AndroidRuntime] com.google.maps.api.android.lib6.common.apiexception.b: Failed to decode image. The provided image must be a Bitmap.
[AndroidRuntime] 	at com.google.maps.api.android.lib6.impl.j.a(:com.google.android.gms.dynamite_mapsdynamite@15090048@15.0.90 (040400-231259764):7)
[AndroidRuntime] 	at com.google.maps.api.android.lib6.impl.q.a(:com.google.android.gms.dynamite_mapsdynamite@15090048@15.0.90 (040400-231259764):5)
[AndroidRuntime] 	at com.google.maps.api.android.lib6.impl.dg.<init>(:com.google.android.gms.dynamite_mapsdynamite@15090048@15.0.90 (040400-231259764):15)
[AndroidRuntime] 	at com.google.maps.api.android.lib6.impl.bf.a(:com.google.android.gms.dynamite_mapsdynamite@15090048@15.0.90 (040400-231259764):385)
[AndroidRuntime] 	at com.google.android.gms.maps.internal.l.a(:com.google.android.gms.dynamite_mapsdynamite@15090048@15.0.90 (040400-231259764):396)
[AndroidRuntime] 	at fw.onTransact(:com.google.android.gms.dynamite_mapsdynamite@15090048@15.0.90 (040400-231259764):4)
[AndroidRuntime] 	at android.os.Binder.transact(Binder.java:608)
[AndroidRuntime] 	at com.google.android.gms.internal.zzeb.zza(Unknown Source:7)
[AndroidRuntime] 	at com.google.android.gms.maps.internal.zzg.addMarker(Unknown Source:9)
[AndroidRuntime] 	at com.google.android.gms.maps.GoogleMap.addMarker(Unknown Source:2)
[AndroidRuntime] 	at com.google.maps.android.MarkerManager$Collection.addMarker(MarkerManager.java:161)
[AndroidRuntime] 	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:842)
[AndroidRuntime] 	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$2100(DefaultClusterRenderer.java:803)
[AndroidRuntime] 	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:642)
[AndroidRuntime] 	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:613)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:105)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:164)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6759)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by mierzynskim** [comment]
@NirmalSubedi17 Can you share an image you're trying to load?
