### ISSUE TITLE
Proposition to change OnClusterClick args

### ISSUE THREAD

**Issue by gnout** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#33]
In the OnClusterClick event, I think that would be very helpful to add to the event args also the collections of pins instead of only the number of pins.

I noticed that in the [ClusterLogicHandler](https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps.Clustering/blob/master/src/Xamarin.Forms.GoogleMaps.Clustering.Android/ClusterLogicHandler.cs#L22) the items count is being added to the args (`cluster.Items.Count`).

My suggestions is to add the `cluster.Items` as a collection of `Pins`. Obviously, the count is not necessary, but removing it might result to "Breaking Changes"

Thanks

**Comment by mierzynskim** [comment]
That's a really good idea! I'll try to add it in the future but I'd also appreciate contributions 🙂
