### ISSUE TITLE
How to add pin that should not be clustered?

### ISSUE THREAD

**Issue by darkovuj** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#34]
Is it possible to add pins that would not be clusered? On some previous version there where to collections of pins ClusteredPins and Pins that did just that. Now ClusteredPins collection is removed so everything in Pins clustered.

**Comment by mierzynskim** [comment]
Unfortunately, it caused too many issues and it's no longer supported. When you install the clustering extension, every pin you add to `Pins` collection is clustered.
