### ISSUE TITLE
Recommended way to load pins

### ISSUE THREAD

**Issue by gabrielbunselmeyer** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#40]
Hey there.

Not quite a bug/feature request, but a question. My current situation is the following:
- Map loads all pins on app start.
- User can filter these pins, removing the appropriate ones.
- If all filters are deselected, the app reloads all pins onto the map.

The first time the pins are loaded (on app load) it takes little over a second. However, whenever it reloads all points on the map after that, it takes up to 6 seconds with just 341 total pins. This is an awful lot of time for such a small number of pins. 

Also important to note this doesn't happen with the base library, and the loading of the same 341 is near instant. Clustering does work great so far.

My PinLoad method isn't really optimized, yet it was glaring to see such an increase in time, as loading has to use the main thread and the screen freezes.

```
private async Task LoadPins(List<Site> siteList) {
            List<Pin> pinList = new List<Pin>();

            var latitudes = new List<double>();
            var longitudes = new List<double>();

            await Task.Run(() =>
            {
                foreach (Site site in siteList)
                {
                    Pin pin = new Pin
                    {
                        Tag = site.SiteId,
                        Label = site.SiteTitle,
                        Address = site.SiteAddress,
                        Position = new Position(site.SitePosition.X, site.SitePosition.Y),
                        Type = PinType.Generic,
                        Icon = BitmapDescriptorFactory.DefaultMarker((Color)App.Current.Resources["MainOrange"])
                    };

                    pinList.Add(pin);

                }
            });
            
            Map.Pins.Clear();

            foreach (Pin pin in pinList)
            {
                Map.Pins.Add(pin);
            }

            CalculateMapZoomDistance(latitudes, longitudes);
}
```

Timing from the beginning of the method to just before CalculateMapZoomDistance is called with a Stopwatch gives me 5.77 seconds. I of course assumed the time needed would be higher than the base library as the clustering takes place, but this seems like too much for such a small number of pins.

Am I doing something wrong? As far as I understand using Device.InvokeOnMainThread for loading the pins inside the async part wouldn't really help.

**Comment by gabrielbunselmeyer** [comment]
We were able to solve our slowdown with a fork removing the following lines on ClusterLogic:

```
protected override void AddItems(IList newItems)
{
    base.AddItems(newItems);
    //clusterManager.Cluster();
}

protected override void RemoveItems(IList oldItems)
{
    base.RemoveItems(oldItems);
    //clusterManager.Cluster();
}
```

I can't really debug the library at the moment, yet I think this AddItems method is called way more than it should when using .Add(pin)? This call to Cluster() slows down the process significantly, as stated before.

Yet it might not be a great solution as the map pins won't refresh on the map until the user moves its camera. For our app it works as whenever the filter changes the camera/zoom is also changed appropriately, but other use cases might not adapt to this too well. Of course you can also call Map.Cluster() yourself after the adding process is done, getting some increased control over the process.

**Comment by mierzynskim** [comment]
Yes, 6 seconds is quite a long time to load a map 😞 . The point is that we're limited by Google's design. As far as I know clustering libraries don't work really well with adding/removing pins. I've added `clusterManager.Cluster()` call to be able to display changes on the map. I'm aware that's quite resource intensive operation but I haven't found a better way yet. I'll try to look for a solution but I'm open for your suggestions and PR 🙂 !

**Comment by gabrielbunselmeyer** [comment]
I think the simplest solution would be to perhaps include both versions? As in, have a parameter in the options to not cluster automatically, with the user having to call map.Cluster() himself after the process of loading the points is finished. I've just tested this manual clustering, and it does work pretty well.

Default could still be your implementation with the automatic clustering, as I imagine it is the better choice on most cases(?).

**Comment by mierzynskim** [comment]
I was also thinking about adding a flag but it may be misleading for some users. Would you be able to provide a sample app showing how exactly you reload pins? There may be a way to optimise it either on my side or on yours

**Comment by gabrielbunselmeyer** [comment]
At the moment all pins are loaded when the app starts, and then the user can interact with them through filters. Selecting a filter removes all pins that aren't related to it. Then, if the user deselects this filter, all pins are loaded again.

The code on the OP is pretty much all of it. There are certainly some optimizations to be made on my end (mainly regarding the usage of different lists, and reloading every one isn't quite the smartest idea), but none of them really relate to this. There isn't much more context that is relevant other than what I've already showed, as the freezing is quite specific, using the main thread when .Add().

I agree that a flag might be somewhat confusing at first glance. Yet it is quite useful in any scenarios where a bunch of pins have to be loaded at runtime/changing/filtering the pins on the map.

I made the adjustements on my fork, if you're interested in taking a look. They are quite simple, only added a property in ClusterOptions and checked it on both ClusterLogic classes.

**Comment by deepblueday** [comment]
I have to concur with @gabrielbunselmeyer as I'm having the exact same problem on a similar scenario.

I have a map bound to a list of "Location" models via "ItemsSource" collection.

Like the below:

```
        <map:ClusteredMap
            x:Name="Map"
            VerticalOptions="FillAndExpand"            
            HasZoomEnabled="true"
            HasRotationEnabled="false"
            MyLocationEnabled="true"
            ItemsSource="{Binding Locations}"
            InitialCameraUpdate="0, 0, 1, 0, 0"
            >
            <map:ClusteredMap.ItemTemplate>
                <DataTemplate>
                    <gmap:Pin Position="{Binding Position}"
                             Address="{Binding Address}"
                             Label="{Binding Description}" />
                </DataTemplate>
            </map:ClusteredMap.ItemTemplate>

        </map:ClusteredMap>
```

If the "Locations" collection is already populated by the time the Map renders (i.e: it is instantiated and populated in the page constructor), then the clustered map adds very little overhead.

Now, if, on the other hand, I add items to the collection after the map has rendered, the map hangs the UI for several seconds.

As a comparison:

Adding 500 elements to the "Locations" collection on page constructor -> Page loads in a second or two.

Code behind below:

```
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using MapsPOC.Helpers;
using MapsPOC.Models;
using Xamarin.Forms;
using Xamarin.Forms.GoogleMaps;
using Xamarin.Essentials;

namespace MapsPOC
{
    public partial class ClusteredMapPreloaded : ContentPage
    {
        readonly int _pinCount = 500;

        readonly ObservableCollection<LocationModel> _locations;        

        public ObservableCollection<LocationModel> Locations => _locations;

        public ClusteredMapPreloaded()
        {
            BindingContext = this;
            _locations = new ObservableCollection<LocationModel>();

            Random rng = new Random();

            for (int i = 0; i < _pinCount; i++)
            {
                //Create new location
                LocationModel locationModel = new LocationModel();
                locationModel.Address = $"Address {i}";
                locationModel.Description = $"Location {i}";
                locationModel.Position = RandomPosition.Next();

                //Add Location
                _locations.Add(locationModel);
            }

            InitializeComponent();
        }

    }
}

```

Adding 500 elements to the "Locations" collection after Map has rendered (triggered by a button in UI) -> Takes somewhere around 45 (!) seconds in the simulator.

Code behind below:

```
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using MapsPOC.Helpers;
using MapsPOC.Models;
using Xamarin.Forms;
using Xamarin.Forms.GoogleMaps;
using Xamarin.Essentials;

namespace MapsPOC
{
    public partial class ClusteredMap : ContentPage
    {
        readonly int _pinCount = 500;

        //readonly ObservableCollection<LocationModel> _locations;
        ObservableCollection<LocationModel> _locations;

        public ObservableCollection<LocationModel> Locations => _locations;

        public ClusteredMap()
        {
            BindingContext = this;
            _locations = new ObservableCollection<LocationModel>();
            InitializeComponent();
        }

        async void OnLoadPinsButtonClicked(object sender, EventArgs args)
        {
            //System.Diagnostics.Debug.WriteLine("OnButtonClicked");
            MainThread.BeginInvokeOnMainThread(LoadPins);
        }

        protected void LoadPins()
        {
            System.Diagnostics.Debug.WriteLine("LoadPins begin");
            Stopwatch stopwatch = new Stopwatch();
            stopwatch.Start();

            Random rng = new Random();

            for (int i = 0; i < _pinCount; i++)
            {
                //Create new location
                LocationModel locationModel = new LocationModel();
                locationModel.Address = $"Address {i}";
                locationModel.Description = $"Location {i}";
                locationModel.Position = RandomPosition.Next();

                //Add Location
                _locations.Add(locationModel);
            }

            stopwatch.Stop();
            System.Diagnostics.Debug.WriteLine($"LoadPins end - {stopwatch.ElapsedMilliseconds} ms");
        }
    }
}


```

The overall process is the same. The only difference is that, in one scenario, by the time the Map is instantiated/rendered the bound collection has all the elements it needs, whereas on the other scenario, we do that process after map is rendered - triggered by a button in UI.

I'm thinking...could you possibly leverage the standard "BatchBegin" and "BatchCommit" methods? So that, if I have to add/update/remove a number of elements, I could go like the below:

```
Map.BatchBegin()
...
//Add/Update/Remove bound elements - Map will NOT recalculate clusters
...
Map.BatchCommit() //Now map does recalculate clusters - in one shot, vs for every element added/removed/updated
```
Hope that makes sense.

**Comment by mierzynskim** [comment]
@deepblueday Thanks for sharing this. The problem in your case is that  `_locations ` is `ObservableCollection` and every time you call Add method it triggers clustering. Would you be able to add location models to a normal list and create `ObservableCollection` at the end of the method (see example below)? That may speed up your code. Let me know if it helps.

        protected void LoadPins()
        {
            Random rng = new Random();
            var tempList = new List<LocationModel>();
            for (int i = 0; i < _pinCount; i++)
            {
                //Create new location
                LocationModel locationModel = new LocationModel();
                locationModel.Address = $"Address {i}";
                locationModel.Description = $"Location {i}";
                locationModel.Position = RandomPosition.Next();

                //Add Location
                tempList.Add(locationModel);
            }
            _locations = new ObservableCollection<LocationModel>(tempList);
        }

**Comment by deepblueday** [comment]
@mierzynskim Sorry for the late reply, it's been very busy down here.

Unfortunately your suggested approach does not work. The map does not show any pins with that code. 

I believe the problem is because, when you do a "new" of the ObservableCollection, you are effectively creating a completely different object in-memory. 

So now, the map is bound to an object, and the _locations field is pointing to an entirely different object.

Any ideas?

**Comment by mierzynskim** [comment]
@deepblueday You're right but it was just a concept. You can try to add a setter to Locations property and set it in your method. If it still doesn't work, I'll try to find some time to prepare a full example.
