### ISSUE TITLE
 error only on android when Install clustering

### ISSUE THREAD

**Issue by HectorOCH** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#45]
### VERSIONS

* Xamarin.Forms.GoogleMaps- 3.2.0
* Xamarin.Forms.GoogleMaps.Clustering - 1.0.1
* Xamarin.Forms - 3.6.0.2930
* Android - 9.0

### PLATFORMS

Android

### ACTUAL BEHAVIOR

install the nuget accordingly, when you start the app you start the following error

"java.lang.IllegalArgumentException: already added: Lcom / google / maps / android / projection / Point"

I only have this map in the application and I have a unique version of googleplayservice

### SCREENSHOT
![error_nuget](https://user-images.githubusercontent.com/35742058/61408452-0c8f3b00-a8ae-11e9-9fcb-19a32a35bc48.JPG)

**Comment by mierzynskim** [comment]
Would you be able to provide a reproduction project? I haven't noticed anything like that before

**Comment by HectorOCH** [comment]
yes, it was a mistake of mine, there was an additional map component, which prevented the use
