### ISSUE TITLE
How to change minimum cluster size to 2?

### ISSUE THREAD

**Issue by dejanbasic** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#51]
Hi, I want to set minimum cluster size to 2, because I have cases where two or more markers have the same position. They are overlapping and if there is less then five markers, there is no cluster to indicate that they are one over another.

**Comment by dimbata** [comment]
I would also like to know how to implement this

**Comment by jendang** [comment]
I also want to implement this.

**Comment by jpaquete** [comment]
Exact same issue ! Cluster size is 5. How can it be changed to 2 ?... Did you manage figure out ? Otherwise working great. Excelent work ! Many thanks!

**Comment by jpaquete** [comment]
ok responding my own question one can add the following line on the constructor of ClusterRenderer as a quick fix. compile it and then replace Xamarin.Forms.GoogleMaps.Clustering.Android.dll on the project. Did test it OK for android. iOS has a similar approach(there is a readonly property minimumClusterSize = 5);

this.MinClusterSize = 1;

Just to help you guys quickly. May the project owner can expose this property in the next version. Thanks again

**Comment by mierzynskim** [comment]
Sorry for the late reply. @jpaquete your solution should work fine. Would you be able to create PR for it?

**Comment by jpaquete** [comment]
ok short on time right now... will try to do it next week for both iOS and Android.

**Comment by mierzynskim** [comment]
Ok @jpaquete, I've found some time and created a PR for it https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps.Clustering/pull/52. Does it fit your needs?

**Comment by jpaquete** [comment]
Tks mierzynskim sure it fits. Is it also working for iOS and on the nugget package ?

**Comment by jendang** [comment]
I am using nugget package, how to use it? Thanks

**Comment by jpaquete** [comment]
Hey @mierzynskim we are using the nugget package. Will it be updated also ?Tks!

**Comment by mierzynskim** [comment]
Yes, I'll try to release a new version soon

**Comment by jpaquete** [comment]
Hey Michal how are you ? Can you update the nugget package
for Xamarin.Forms.GoogleMaps.Clustering? Sorry to bother I have an urgent
deadline :(
I will buy a huge beer if you visit Lisbon ;)

**Comment by mierzynskim** [comment]
The nuget package has been updated. You should be able to change minimum cluster size.

**Comment by jendang** [comment]
> The nuget package has been updated. You should be able to change minimum cluster size.

@mierzynskim  Thanks a lot! it works perfectly!!!
