### ISSUE TITLE
Some custom pin icons displayed as standard icons

### ISSUE THREAD

**Issue by z-dmitri** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#7]
Some custom pin icons displayed as standard icons.
After several zoom-in and zoom-out all icons became correct.

Android sample attached.

Please, set AndroidManifest.xml Google API key first: 
<meta-data android:name="com.google.android.geo.API_KEY" android:value="GOOGLE MAP KEY"

"await Task.Delay(1000);" after each "Map.ClusteredPins.Add(pin);" could increase amount of correctly displayed icons. 

Sample to reproduce:
[GMaps.zip](https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps.Clustering/files/2860153/GMaps.zip)

**Comment by alex-relov** [comment]
I have exactly the same problem. XF 3.5 Adroid 9

**Comment by mierzynskim** [comment]
Thanks for the sample project! I have identified the issue and I'm going to look for a solution
