### ISSUE TITLE
ClusterdPins not update on view

### ISSUE THREAD

**Issue by kingnguyen1993** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#8]
When i change item in collection, view not change until i zoom in or zoom out.
Here my code.
`        <clustering:ClusteredMap
            x:Name="Map"
            HorizontalOptions="FillAndExpand"
            VerticalOptions="FillAndExpand">
            <clustering:ClusteredMap.Behaviors>
                <bindings:BindingClusteredPinsBehavior Value="{Binding ClusteredPins}" />
            </clustering:ClusteredMap.Behaviors>
        </clustering:ClusteredMap>

On ViewModel

            Device.BeginInvokeOnMainThread(() =>
                {
                    ClusteredPins.Clear();

                    for (var i = 0; i < ClusterItemsCount; i++)
                    {
                        ClusteredPins.Add(new Pin()
                        {
                            Type = PinType.Place,
                            Position = GetRandomLocation(),
                            Label = $"Item {i}",
                            //Icon = BitmapDescriptorFactory.FromBundle("image01.png")
                        });
                    }
                });
`

**Comment by mierzynskim** [comment]
It's probably a limitation of google maps utils 😞 https://github.com/googlemaps/google-maps-ios-utils/issues/26. You can try to call `Map.Cluster()` after you update pins collection.

**Comment by kingnguyen1993** [comment]
Thanks. I already know that. I'm testing performent now. :)

**Comment by mierzynskim** [comment]
Reopening because the problem appears on both Android and iOS. @kingnguyen1993 Did you test how a hack with calling `Cluster` method affects performance?
